# Generated by Django 3.2.25 on 2025-09-28 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeats', '0017_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
